-- Pandoc custom writer: Markdown letter -> GNU groff MM (blocked letter, ".LT BL")
-- Front matter: author, opening, to (one address line per line), signature, date.
-- The last paragraph of the body is used as the complimentary close.

local stringify = pandoc.utils.stringify

local function esc(s)
  s = s:gsub('\\', '\\e'):gsub('\u{00A0}', '\\~')
  -- a leading "." or "'" would be read as a roff request
  if s:match("^[.']") then s = '\\&' .. s end
  return s
end

local function q(s) return '"' .. s:gsub('"', '""') .. '"' end

local inlines, blocks

local function inline(el)
  local t = el.t
  if t == 'Str' then return esc(el.text)
  elseif t == 'Space' then return ' '
  elseif t == 'SoftBreak' then return '\n'
  elseif t == 'LineBreak' then return '\n.br\n'
  elseif t == 'Emph' then return '\\fI' .. inlines(el.content) .. '\\fP'
  elseif t == 'Strong' then return '\\fB' .. inlines(el.content) .. '\\fP'
  elseif t == 'Code' then return '\\f[CR]' .. esc(el.text) .. '\\f[P]'
  elseif t == 'Quoted' then
    local l, r = '\u{201C}', '\u{201D}'
    if el.quotetype == 'SingleQuote' then l, r = '\u{2018}', '\u{2019}' end
    return l .. inlines(el.content) .. r
  elseif t == 'Link' then
    return '\\c\n.pdfhref W -D ' .. q(el.target) .. ' -- ' .. q(stringify(el.content)) .. '\n'
  elseif t == 'Note' then
    local paras = {}
    for _, b in ipairs(el.content) do paras[#paras + 1] = inlines(b.content or pandoc.Inlines{pandoc.Str(stringify(b))}) end
    return '\\*F\\c\n.FS\n' .. table.concat(paras, '\n.sp\n') .. '\n.FE\n'
  elseif t == 'Span' or t == 'SmallCaps' or t == 'Underline' then return inlines(el.content)
  else return esc(stringify(el)) end
end

function inlines(list)
  local out = {}
  for _, el in ipairs(list) do out[#out + 1] = inline(el) end
  return table.concat(out)
end

local function block(el)
  local t = el.t
  if t == 'Para' or t == 'Plain' then return '.P\n' .. inlines(el.content) .. '\n'
  elseif t == 'BlockQuote' then return '.DS I\n' .. blocks(el.content) .. '.DE\n'
  else return '.P\n' .. esc(stringify(el)) .. '\n' end
end

function blocks(list)
  local out = {}
  for _, el in ipairs(list) do out[#out + 1] = block(el) end
  return table.concat(out)
end

local function lines(meta)
  -- split a multi-line metadata value on its line breaks
  local out, cur = {}, {}
  for _, el in ipairs(pandoc.utils.blocks_to_inlines(pandoc.utils.type(meta) == 'Inlines' and pandoc.Blocks{pandoc.Plain(meta)} or meta)) do
    if el.t == 'SoftBreak' or el.t == 'LineBreak' then
      out[#out + 1] = stringify(pandoc.Inlines(cur)); cur = {}
    else cur[#cur + 1] = el end
  end
  out[#out + 1] = stringify(pandoc.Inlines(cur))
  return out
end

local function long_date(s)
  local y, m, d = tostring(s):match('^(%d+)-(%d+)-(%d+)')
  if not y then return tostring(s) end
  return os.date('%B %d, %Y', os.time{year = tonumber(y), month = tonumber(m), day = tonumber(d), hour = 12}):gsub(' 0', ' ')
end

function Writer(doc, opts)
  local meta = doc.meta
  local body = pandoc.List(doc.blocks)
  local closing = ''
  if #body > 0 and body[#body].t == 'Para' then
    closing = inlines(body[#body].content)
    body:remove(#body)
  end

  local out = {}
  local function add(s) out[#out + 1] = s end
  local from = meta.author and stringify(meta.author) or ''
  add('.\\" Generated by letter.lua; compile with groff -k -Tpdf -mm\n')
  add('.ds PDFHREF.COLOUR 0.35 0.00 0.60\n.ds PDFHREF.BORDER 0 0 0\n')
  add('.ds HF "3 3 2 2 2 2 2"\n')
  add('.LT BL\n')
  if meta.date then add('.ND ' .. q(long_date(stringify(meta.date))) .. '\n') end
  -- the .WA argument is the name used by .SG; the block is the sender address printed in the header
  add('.WA ' .. q(from) .. '\n' .. esc(from) .. '\n.WE\n')
  if meta.to then
    local to = lines(meta.to)
    add('.IA\n')
    for _, l in ipairs(to) do if l ~= '' then add(esc(l) .. '\n') end end
    add('.IE\n')
  end
  add('.LO SA ' .. q(meta.opening and stringify(meta.opening) or '') .. '\n')
  add('.LO SJ ' .. q(meta.title and stringify(meta.title) or '') .. '\n')
  -- must follow the letter header macros, or the header is pushed after the body
  add('.pdfinfo /Title ' .. q(stringify(meta.title or '')) .. '\n')
  add('.pdfinfo /Author ' .. q(from) .. '\n')
  add(blocks(body))
  add('.FC ' .. q(closing) .. '\n')
  add('.SG\n')
  return table.concat(out)
end
