name: Build and Deploy Jekyll
on:
  push:
    branches:
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: source
      
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-2-

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          sudo apt install pandoc groff -y

      - name: Build
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build posts as PDF
        run: |
          [ ls _posts/*.md >/dev/null 2>&1 ] || exit 0
          for f in _posts/*.md; do
            filename=${f##_posts/}
            filename=${filename%%.md}
            year=`echo $filename | cut -d- -f1`
            month=`echo $filename | cut -d- -f2`
            day=`echo $filename | cut -d- -f3`
            basename=`echo $filename | cut -d- -f4-`
            sed 's/\(\[.*\](.*)\){.*}/\1/g;s/excerpt:/abstract:/;s/tags:/keywords:/' "$f" | \
              sed 's/## /# /;s/### /## /;s/#### /### /;s/##### /#### /;s/###### /##### /' | \
              pandoc - -f markdown -t ms -s | \
              groff -Tpdf -mspdf > "_site/blog/posts/$year/$month/${basename%%.md}.pdf"
          done

      - name: Commit changes
        run: |
          git clone https://espositoandrea:${{ secrets.GITHUB_TOKEN }}@github.com/espositoandrea/espositoandrea.github.io.git --branch master --single-branch master
          rm -fr master/*
          cp -r _site/* master/
          cp -r .well-known master/ # for brave verification
          cd master
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update website" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          directory: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
